config/routes.rb
Rails.application.routes.draw do
  resources :twits
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'twits#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/twit.rb
class Twit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/twits_controller.rb
class TwitsController < ApplicationController
  before_action :set_twit, only: [:show, :edit, :update, :destroy]

  # GET /twits
  # GET /twits.json
  # Полный список твитов
  def index
    @twits = Twit.all
  end

  # GET /twits/1
  # GET /twits/1.json
  # Каждый твит
  def show
  end

  # GET /twits/new
  # Для создания нового твита
  def new
    @twit = Twit.new
  end

  # GET /twits/1/edit
  # Для редактирования существующего твита
  def edit
  end

  # POST /twits
  # POST /twits.json
  # Создает новый твит
  def create
    @twit = Twit.new(twit_params)

    respond_to do |format|
      if @twit.save
        format.html { redirect_to @twit, notice: 'Twit was successfully created.' }
        format.json { render :show, status: :created, location: @twit }
      else
        format.html { render :new }
        format.json { render json: @twit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twits/1
  # PATCH/PUT /twits/1.json
  # Обновляет данные существующего твита
  def update
    respond_to do |format|
      if @twit.update(twit_params)
        format.html { redirect_to @twit, notice: 'Twit was successfully updated.' }
        format.json { render :show, status: :ok, location: @twit }
      else
        format.html { render :edit }
        format.json { render json: @twit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twits/1
  # DELETE /twits/1.json
  # Удаляет существующий твит
  def destroy
    @twit.destroy
    respond_to do |format|
      format.html { redirect_to twits_url, notice: 'Twit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # Устанавливает твит
    def set_twit
      @twit = Twit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    #Перехват заголовка и содержание твита и отправляет в криейт и апдейт
    def twit_params
      params.require(:twit).permit(:tittle, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twits_helper.rb
module TwitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/twits/_form.html.erb
<%= form_for(twit) do |f| %>
  <% if twit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(twit.errors.count, "error") %> prohibited this twit from being saved:</h2>

      <ul>
      <% twit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tittle %>
    <%= f.text_field :tittle %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/twits/edit.html.erb
<h1>Editing Twit</h1>

<%= render 'form', twit: @twit %>

<%= link_to 'Show', @twit %> |
<%= link_to 'Back', twits_path %>

app/views/twits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Twits</h1>

<table>
  <thead>
    <tr>
      <th>Tittle</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @twits.each do |twit| %>
      <tr>
        <td><%= twit.tittle %></td>
        <td><%= twit.content %></td>
        <td><%= link_to 'Show', twit %></td>
        <td><%= link_to 'Edit', edit_twit_path(twit) %></td>
        <td><%= link_to 'Destroy', twit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Twit', new_twit_path %>

app/views/twits/new.html.erb
<h1>New Twit</h1>

<%= render 'form', twit: @twit %>

<%= link_to 'Back', twits_path %>

app/views/twits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tittle:</strong>
  <%= @twit.tittle %>
</p>

<p>
  <strong>Content:</strong>
  <%= @twit.content %>
</p>

<%= link_to 'Edit', edit_twit_path(@twit) %> |
<%= link_to 'Back', twits_path %>